### ISSUE TITLE
Hyplotype identification in the network

### ISSUE THREAD

**Issue by quant42** [eeg-ebe/HaplowebMaker#1]
Make it possible to identify the haplotypes in the network.

**Comment by jflot** [comment]
When the cursor stays for 1-2 seconds without moving on top of an haplotype circle, a box should pop up telling the name(s) of the sequence(s) corresponding to this haplotype.

**Comment by quant42** [comment]
I'm not a fan of any action that requires 1-2 seconds in order to come up. There are always two problems with it. If you want to work fast, 1-2 seconds is too slow. If you want to think about something, it is nasty that after 1-2 seconds a dialog pops up ... And if you touch your cursor by only a bit, you may have to re-wait. Apart from that if you use the website on your cellphone you don't necessarily have a cursor that can stay over an object for 1-2 seconds (not that I would suggest you to do so - but some guys will certainly do that) ...

I added that the dialog pops up, when you right click the object. (The dialog itself does not show much till now - only the id of the node. The content of the dialog is certainly worth a some improvements - that is why I do not close the ticket until now ...)

**Comment by jflot** [comment]
Having a pop-up is fine I think. However, I suggest that the pop-up should appear next to the node where the user just clicked, not on the side of the haploweb. Also, the box should include the name of the sequences corresponding to the haplotype (having to search for this information in the textual description of the haplotype would be not so convenient for users).
As a side note, calling each haplotype Id1, Id2, Id3... is not very standard, I suggest replacing it with H1, H2, H3 which is the standard way in population genetics (with "H" standing for "haplotype").
