### ISSUE TITLE
Add buttons to increase line thickness and curve thickness

### ISSUE THREAD

**Issue by jflot** [eeg-ebe/HaplowebMaker#14]
Right now it is possible to increase and decrease the circle dimensions, but it would be great to have pairs of buttons to do the same for the thickness of the straight lines connecting haplotypes as well as for the thickness of the curves representing heterozygous individuals. Pressing the "++" button would multiply the thickness of all the lines or curves by a certain factor, and pressing the "--" button would divide it.

**Comment by quant42** [comment]
Done
