### ISSUE TITLE
add an option to remove singletons

### ISSUE THREAD

**Issue by jflot** [eeg-ebe/HaplowebMaker#17]
When working with invasive species (or any species that experienced a recent range expansion) there are a lot of singletons, i.e. haplotypes found only in one individuals, and this results in haplowebs that are very difficult to read. To avoid this, it would be great to add a button that removes all singleton haplotypes from the analysis (i.e., individuals having both a "regular" haplotype and a singleton one will appear as homozygous in the haploweb, whereas individuals having two singleton haplotypes will completely disappear from the graph).

**Comment by quant42** [comment]
Actually we need two options here right? One is to filter out all haplotypes that occur less then n times in the complete dataset and the other one is to filter out all haplotypes that occur in less then n individuals.

**Comment by jflot** [comment]
Yes, it would be nice.

**Comment by jflot** [comment]
Done.
