### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by quant42** [eeg-ebe/HaplowebMaker#22]
Well some of the code was written in a bit of haste and is not as universal/clear as it should be.

Clean it up!

**Comment by jflot** [comment]
We need to make the calculation faster (notably when no haploweb is needed, only the conspecificity matrix).

**Comment by jflot** [comment]
Still on the todo-list.

**Comment by jflot** [comment]
Actually a duplicate of #37, hence I close it.
