### ISSUE TITLE
Add a mapping file

### ISSUE THREAD

**Issue by quant42** [eeg-ebe/HaplowebMaker#34]
Add a mapping file describing which input file has been renamed into which other file name.

**Comment by jflot** [comment]
Is it really necessary to rename the files? This will be problematic for users, as it is unwieldy to have to check the content of the filenamemappings.dat file to attribute each file to each marker. It would be much better if the names of the input files are used for the outputs; if some renaming cannot be avoided, then maybe we could just append something after the original part of the filename (e.g. originalname_newpart)?

**Comment by quant42** [comment]
The original file name may contain characters that can break a script or somehow represent a security risk. This is more a problem from files coming from a linux os than from a windows os - since it is totally valid to have characters like '*', '?', '<', '>' etc. present in Linux files ... but files on Windows are not allowed to contain such characters. Also with the multi file upload it is (tricky but) possible to upload multiple files from different folders. It is then possible that two (or more files) share the same file name - which results in multiple files overwriting each other. Via the file renaming I'm preventing such issues ... but maybe it is possible to do this a bit less restrictive ... I will reopen the issue and evaluate/implement another method.

**Comment by jflot** [comment]
I see... A possibility would be to remove all non-alphanumerical characters from the filenames, then append a number ("_1", "_2", etc.) specifying the order in which the files were uploaded - I guess that it would remove the security risk and the problem of having several files with identical names, while at the same time making it possible for users to identify easily their input files in the names of the output files).

**Comment by quant42** [comment]
At the moment it is a bit like this. It is "secured original name till first ."_"nr".fa, where all non alpha numerical characters have been replaced by a "X".

**Comment by jflot** [comment]
It sounds perfect, except that I would rather go till the last dot (unless this poses a security problem) as users may have put important information after the first dot. Also, in Linux it could be that there is no dot at all, so we need to make sure that this would not break the script.

**Comment by quant42** [comment]
It does not break the script if there's no dot at all ... This is a case that I already tested yesterday.

**Comment by quant42** [comment]
Better to only rename files internally but when they are getting served - use original names ...

**Comment by quant42** [comment]
Not needed anymore - files get renamed internally but are shown with the original file name in the zip / when downloaded ....

solved with commit 40e6b23195e79c3ab780eb69bd8d7316e1837e29 / 6ec86efbdc2a3951b2b2a355b122a43de02c6e0b
