### ISSUE TITLE
output tab-delimited conspecificity matrix in addition to SVG

### ISSUE THREAD

**Issue by jflot** [eeg-ebe/HaplowebMaker#38]
It would be nice to have the pipeline output the (numerical) tab-delimited matrix so that users can process it using e.g. R and their favorite clustering approach.

**Comment by quant42** [comment]
solved with commit 40e6b23195e79c3ab780eb69bd8d7316e1837e29 / 6ec86efbdc2a3951b2b2a355b122a43de02c6e0b
