### ISSUE TITLE
Input a list of individuals + colours

### ISSUE THREAD

**Issue by jflot** [eeg-ebe/HaplowebMaker#6]
Add the possibility to input as a second file (in addition to the main FASTA) a tab-delimited list of individuals (with for each of them an associated colour). The second column should not be compulsory. As a result, only the individuals mentioned in the list will be used for the haploweb analysis and the other individuals will be skipped (also for the network construction phase): this will make it easier to e.g. exclude distantly related outgroups that may be useful for phylogenetic trees but are annoying when drawing a network. If there is a second column, then each haplotype will be coloured according to the list (this will require that pie charts be implemented, since some haplotypes may be shared between individuals with different colours).

**Comment by quant42** [comment]
Isn't it better to do it the other way round? Input a file that contains the individuals (or better alleles) that should not get processed?

**Comment by jflot** [comment]
I think that most users will prefer to specify the individuals to be used rather than the individuals to be excluded. Also, it makes it easier as one need only to input one file (otherwise we would need one file for the colors and one file for the individuals to be excluded, and the two lists would be somehow redundant as they would be each other's complementary).

**Comment by quant42** [comment]
Hmm, also if they have multiple fasta input files? Anyway we can do both ...

**Comment by jflot** [comment]
Yes, my idea is that there should be only one input file telling (for all markers) which individuals to include and what color to attribute to each of them.
